### ISSUE TITLE
Enhancement: call assessment query for agent for Wilo Pilot KPI

### ISSUE THREAD

**Issue by reinhardkurz** [wardhanster/blinkin-features-n-issues#12]
Create a query to collect the data for pilot KPI, which appears on agent screen when call has ended and which must be completed after each call.

German version:
Ja/Nein (yes/no)
- Wurde das Problem des Kunden gelöst? 
- War BlinkIn für die Bearbeitung hilfreich?
(only if this is confirmed yes, the following yes/no questions appear)
- War die Bearbeitungszeit mit BlinkIn kürzer?
- Wurde ein Gewährleistungsfall verhindert?
- War BlinkIn für die Vorbereitung eines Vor-Ort-Einsatzes hilfreich?
- Wurde ein Vor-Ort-Einsatz eingespart?

Skala 1-3 (scale 1-3)
- Wie empfand der Kunde den Einsatz von BlinkIn?
- Wie bewerten Sie die Audioqualität des Gesprächs?
- Wie bewerten Sie die Videoqualität des Gesprächs?

English version:
yes/no questions:
- Has the problem of the customer been solved?
- Was BlinkIn helpful for this case? 
(only if this is confirmed yes, the following yes/no questions appear)
- Was the processing time shorter with BlinkIn? 
- Was a warranty case prevented?
- Was BlinkIn useful for the preparation of an on-site-visit?
- Has an on-site visit been saved?

scale 1-3 questions:
- How did the customer feel about using BlinkIn?
- How do you rate the audio quality of this call?
- How do you rate the video quality of this call?

Scale definition:
1 = not good / nicht gut
2 = okay
3 = very good / sehr gut

**Comment by wardhanster** [comment]
Implemented and tested.
