### ISSUE TITLE
Bug: login problems and aborted sessions this morning (SMS delivered, client enters invalid session without notification)

### ISSUE THREAD

**Issue by reinhardkurz** [wardhanster/blinkin-features-n-issues#28]
after I had cleared cache on Chrome I had to refresh several times to get back to the login page; Wilo login environment was not displayed at first, I saw none of the CI visuals; my first two login attempts did not go through, the page kept loading for 30 sec - then I refreshed both times; 
<img width="1187" alt="Bildschirmfoto 2019-08-05 um 08 04 13" src="https://user-images.githubusercontent.com/53189579/62445904-b3565100-b761-11e9-8d6c-2c07fa34f5ca.png">

with my next attempt I saw the correct Wilo login page and was able to continue to the platform

my first two call attempts were aborted "new session has not been/could not be created" on the agent side, both times I send the SMS nevertheless and it was delivered to the client where the video call started without the client knowing that the agent is not there

--> when new session is "not created" the notification needs to stay on the agent screen, because you may easily overlook the notification; I'd prefer it if there was a notification for like 10 seconds and then the agent is redirected to the mission control page so they have to start new session under all circumstances (of course agent can close the session manually and start a new one within the 10 sec time frame)
--> when there is an error in creating a new session, sending that SMS and copying the particular session link should not be possible

**Comment by wardhanster** [comment]
@reinhardkurz can you also attach a screenshot of the console when you faced this kind of issue ?
I mean when you face this again.
It seems like there was a momentary disconnection from the servers leading to failing login attempts.
I'll keep this ticket open and in needing more information state for now.

**Comment by wardhanster** [comment]
@reinhardkurz closing this issue since there were no more similar incident reports.
If this happens again- feel free to close this ticket.
