### ISSUE TITLE
Bug: Manual torch activation does not work during call on iOS

### ISSUE THREAD

**Issue by reinhardkurz** [wardhanster/blinkin-features-n-issues#5]
issue was reported as general bug by Wilo
we just reproduced the issue on iPhone 5s (iOS: 12.1.2): you can access the swipe menu, but the torch activation button does not react

**Comment by reinhardkurz** [comment]
addition: if you activate the torch before the call, the torch will go out as soon as the client allows camera access for BlinkIn connection

**Comment by wardhanster** [comment]
It's an ios restriction.

**Comment by wardhanster** [comment]
Evaluating a solution to this

**Comment by wardhanster** [comment]
For iOS we will disable the torch option all together.
